### ISSUE TITLE
Erro no login

### ISSUE THREAD

**Issue by lmarcals** [pauloporto/reserva-de-salas#2]
Boa tarde Paulo!

Instalei o projeto, porém, ao tentar acessá-lo, apresenta o erro: Access denied for user ''@'localhost' (using password: NO)
Estou testando com o usuário 'teste' e senha 'teste'. A impressão que dá, é que a variável não está buscando o usuário.

Pode ajudar?

**Comment by pauloporto** [comment]
bom dia! feita a correção no código. Caso der erro novamente por favor pode comentar. Vlws.
